name: Build and deploy Doxygen documentation

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Build Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
          working-directory: '/submodule'
          doxyfile-path: './Doxyfile'
        
    - name: Deploy Doxygen
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: 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
        publish_dir: ./public

  
    # Build Doxygen documentation
    # mattnotmitt/doxygen-action
    # https://github.com/marketplace/actions/doxygen-action

    # Deploy Doxygen documentation
    # peaceiris/actions-gh-pages
    # https://github.com/peaceiris/actions-gh-pages